// This file is auto-generated by @hey-api/openapi-ts

export const $Link = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        target: {
            type: 'string',
            nullable: true
        },
        isExternal: {
            type: 'boolean'
        },
        url: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $SearchResult = {
    type: 'object',
    properties: {
        contentType: {
            type: 'string'
        },
        contentTypeDisplay: {
            type: 'string'
        },
        url: {
            '$ref': '#/components/schemas/Link'
        },
        title: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    additionalProperties: false
} as const;