// This file is auto-generated by @hey-api/openapi-ts

export type Link = {
    name?: string | null;
    target?: string | null;
    isExternal?: boolean;
    url?: string | null;
};

export type SearchResult = {
    contentType?: string;
    contentTypeDisplay?: string;
    url?: Link;
    title?: string;
    summary?: string;
    tags?: Array<(string)>;
};

export type GetV1SearchData = {
    pageNumber?: number;
    pageSize?: number;
    query?: string;
    sort?: string;
    tags?: Array<(string)>;
};

export type GetV1SearchResponse = Array<SearchResult>;

export type $OpenApiTs = {
    '/v1/search': {
        get: {
            req: GetV1SearchData;
            res: {
                /**
                 * Success
                 */
                200: Array<SearchResult>;
            };
        };
    };
};