// This file is auto-generated by @hey-api/openapi-ts

export type SearchQuery = {
    query?: string | null;
    pageNumber?: number;
    pageSize?: number;
    sort?: string | null;
    tags?: Array<(string)> | null;
};

export type SearchResult = {
    contentType?: string;
    contentTypeDisplay?: string;
    url?: string;
    title?: string;
    summary?: string;
    tags?: Array<(string)>;
};

export type SearchResults = {
    total?: number;
    results?: Array<SearchResult>;
    queryOptions?: SearchQuery;
    tags?: Array<SearchTag>;
};

export type SearchTag = {
    text?: string;
    count?: number;
};

export type GetV1SearchData = {
    pageNumber?: number;
    pageSize?: number;
    query?: string;
    sort?: string;
    tags?: Array<(string)>;
};

export type GetV1SearchResponse = SearchResults;

export type GetV1SearchTagsResponse = Array<SearchTag>;

export type $OpenApiTs = {
    '/v1/search': {
        get: {
            req: GetV1SearchData;
            res: {
                /**
                 * Success
                 */
                200: SearchResults;
            };
        };
    };
    '/v1/search/Tags': {
        get: {
            res: {
                /**
                 * Success
                 */
                200: Array<SearchTag>;
            };
        };
    };
};