// This file is auto-generated by @hey-api/openapi-ts

export type SearchOptions = {
    query?: string;
    pageNumber?: number;
    pageSize?: number;
    sort?: string;
    tags?: Array<(string)>;
};

export type SearchResult = {
    contentType?: string;
    contentTypeDisplay?: string;
    url?: string;
    title?: string;
    summary?: string;
    tags?: Array<(string)>;
};

export type SearchResults = {
    total?: number;
    results?: Array<SearchResult>;
    options?: SearchOptions;
};

export type GetV1SearchData = {
    pageNumber?: number;
    pageSize?: number;
    query?: string;
    sort?: string;
    tags?: Array<(string)>;
};

export type GetV1SearchResponse = SearchResults;

export type $OpenApiTs = {
    '/v1/search': {
        get: {
            req: GetV1SearchData;
            res: {
                /**
                 * Success
                 */
                200: SearchResults;
            };
        };
    };
};